services:
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=https://special-space-adventure-q77q74gjp5w42r77-8000.app.github.dev
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=https://special-space-adventure-q77q74gjp5w42r77-8000.app.github.dev
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"