apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: password-checker-certificate
spec:
  secretName: tls-cert
  dnsNames:
  - devops-maestro.xyz
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer