apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rajdeep_deogharia@outlook.com
    privateKeySecretRef:
      name: pwned-secret-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx