apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: password-checker-ingress
spec:
  tls:
  - hosts:
    - app.devops-maestro.xyz
    secretName: tls-cert
  ingressClassName: nginx
  rules:
  - host: app.devops-maestro.xyz
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80